EXPECTED_LOGO_SRC = 'http://dev.anrex.new.maslovart.beget.tech/local/templates/anrex/img/logo.svg'
CITY = 'Москва'
HOVER = 'Время работы с 10.00 до 21.00'
TITLE_BACK_CALL = 'Заявка на обратный звонок'
CALLBACK_POPUP_TITLE = 'Ваша заявка будет направлена нашим менеджерам, мы свяжемся с Вами в ближайшее время.'
CALLBACK_TITLE = 'Ваша заявка была направлена нашим менеджерам, мы свяжемся с Вами в ближайшее время.'
NAME_PLACEHOLDER = 'Антон'
PHONE_PLACEHOLDER = '+7 (960) 345-44-19'
NAME = 'Я'
NAME_CALLBACK = 'Ян'
PHONE = '+79999999999'
PHONE_NEGATIVE = '+799999999999'
RUSSIAN_LETTERS = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'
DISPLAYS_PHONE = '8-495-009-12-34'
SEARCH = 'http://www.w3.org/2000/svg'
CATALOG = 'Каталог'
FURNITURE_AND_ROOM = [
    'По типу мебели Тумбы Шкафы Комоды Кровати и матрасы Столы Витрины Полки Зеркала Вешалки Аксессуары Смотреть '
    'всё По комнате Прихожие Спальни Гардеробные Детские Кабинеты Гостиные Столовые']
COLLECTIONS = 'Коллекции'
DELIVERY = 'Покупателям'
DELIVERY_LIST = ['Доставка и сборка Гарантия на мебель Адреса магазинов']
SALE = 'Скидки'