EXPECTED_LOGO_SRC = 'http://dev.anrex.new.maslovart.beget.tech/local/templates/anrex/img/logo.svg'
CITY = 'Москва'
HOVER = 'Время работы с 10.00 до 21.00'
TITLE_BACK_CALL = 'Заявка на обратный звонок'
CALLBACK_POPUP_TITLE = 'Ваша заявка будет направлена нашим менеджерам, мы свяжемся с Вами в ближайшее время.'
NAME_PLACEHOLDER = 'Антон'
PHONE_PLACEHOLDER = '+7 (960) 345-44-19'
NAME = 'Я'
