name: Python Selenium Tests

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Selenium
      run: pip install selenium

    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest tests/test_title_city.py --alluredir=allure-results
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg2 wget
        wget -qO - https://repo.maven.apache.org/maven2/io/qameta/allure/allure/2.20.1/allure-2.20.1.deb.asc | sudo gpg --dearmor > allure.gpg
        sudo install -o root -g root -m 644 allure.gpg /usr/share/keyrings/allure-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/allure-keyring.gpg] https://repo.maven.apache.org/maven2/io/qameta/allure/allure/2.20.1 allure-bintray/" | sudo tee /etc/apt/sources.list.d/allure.list
        sudo apt-get update
        sudo apt-get install -y allure
    - name: Install curl
      run: sudo apt-get install curl
    - name: Generate Allure Report
      run: allure generate --clean ./allure-results -o allure-report
    - name: Send Allure Report to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        status=$(allure-results/environment.properties | grep 'Status:' | awk -F':' '{print $2}' | tr -d ' ')
        if [ "$status" == "Passed" ]; then
          message="Тесты успешно пройдены! Ссылка на отчет Allure: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        else
          message="Тесты не пройдены. Ссылка на отчет Allure: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        fi
        curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "'$TELEGRAM_CHAT_ID'", "text": "'$message'"}' https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage