name: Python Selenium Tests

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Selenium
      run: pip install selenium

    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
