name: Python Selenium Tests

# Запускаем тесты после push
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Selenium
      run: pip install selenium

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -N "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        rm ~/chromedriver_linux64.zip
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run tests with Xvfb
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' pytest
