name: Python Selenium Tests

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Selenium
      run: pip install selenium

    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest tests/test_title_city.py --alluredir=allure-results
    - name: Install Allure
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
    - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
    - name: Install curl
      run: sudo apt-get install curl
    - name: Generate Allure Report
      run: allure generate --clean ./allure-results -o allure-report
    - name: Read Allure Status
      run: |
        status=$(allure-results/environment.properties | grep 'Status:' | awk -F':' '{print $2}' | tr -d ' ')
        if [ "$status" == "Passed" ]; then
          message="Тесты успешно пройдены! Ссылка на отчет Allure: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        else
          message="Тесты не пройдены. Ссылка на отчет Allure: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        fi
        echo "::set-output name=message::$message"
    - name: Send Allure Report to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "'$TELEGRAM_CHAT_ID'", "text": "${{ steps.read-allure-status.outputs.message }}"}' https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage
