name: Python Selenium Tests
on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Selenium
        run: pip install selenium

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/test_title_city.py

      - name: Install Allure Command Line
        run: wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.zip && unzip allure-commandline-2.14.0.zip && sudo mv allure-2.14.0/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Send Allure report to Telegram
        run: allure report send --report-dir=allure-report \
          --telegram-bot-token=${{ secrets.TELEGRAM_BOT_TOKEN }} --telegram-chat-id=${{ secrets.TELEGRAM_CHAT_ID }}